version: 2
updates:
  - package-ecosystem: "cargo"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "all"
        dependency-type: "direct"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
