[package]
name = "h4bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.74"
shuttle-serenity = "0.24.0"
shuttle-runtime = "0.24.0"
serenity = { version = "0.11.6", default-features = true, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
  "framework",
  "standard_framework",
  "voice",
] }
songbird = { version = "0.3.2" }
shuttle-secrets = "0.24.0"
tokio = "1.31.0"
tracing = "0.1.37"
