[package]
name = "h4bot"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "h4bot"
path = "src/main.rs"

[workspace]

[dependencies]
anyhow = "1.0.75"
shuttle-serenity = "0.26.0"
shuttle-runtime = "0.26.0"
serenity = { version = "0.11.6", default-features = true, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
  "framework",
  "standard_framework",
  "voice",
  "builder",
] }
rustube = { version = "0.6.0", features = ["tokio"] }
songbird = { version = "0.3.2", features = ["yt-dlp", "builtin-queue"] }
shuttle-secrets = "0.26.0"
tokio = "1.32.0"
tracing = "0.1.37"
futures = "0.3.28"
regex = "1.9.3"
url = "2.4.0"
rand = { version = "0.8.5" }
