[package]
name = "h4bot"
version = "0.1.0"
edition = "2021"

[commands]
path = "./commands/*"

[[bin]]
name = "h4bot"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
shuttle-serenity = "0.24.0"
shuttle-runtime = "0.24.0"
serenity = { version = "0.11.6", default-features = true, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
  "framework",
  "standard_framework",
  "voice",
] }
rustube = { version = "0.6.0", features = ["tokio"] }
songbird = { version = "0.3.2" }
shuttle-secrets = "0.24.0"
tokio = "1.32.0"
tracing = "0.1.37"
futures = "0.3.28"
rand = { git = "https://github.com/rust-random/rand.git", rev = "ff121cff61dfcb8c06a618b204ed93be727c4303" }
